# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'MusicRoom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicRoom
  pod 'FacebookCore', '0.3.0'
  pod 'FacebookLogin', '0.3.0'
  pod 'Google'
  pod 'Google/SignIn'
end

