# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'MusicRoom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicRoom
  pod 'FacebookLogin', '0.3.0'
  pod 'FacebookCore', '0.3.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['FacebookLogin'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
