# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'MusicRoom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicRoom
  pod 'FBSDKCoreKit', '~>4.38.0'
  pod 'FBSDKLoginKit', '~>4.38.0'
  pod 'FacebookCore', '0.5.0'
  pod 'FacebookLogin', '0.5.0'
  pod 'GoogleSignIn', '4.4.0'
  pod 'Alamofire', '4.8.0'
  pod 'Socket.IO-Client-Swift', '~> 13.3.0'
  pod 'Starscream', '<= 3.0.5'
end

